project:
  type: website
  output-dir: _site

website:
  title: "Sun Data Analytics Apps"
  favicon: assets/logos/sda-mark.svg
  navbar:
    background: white
    pinned: false
    search: false
    logo: assets/logos/sda-mark.svg
    logo-alt: "Sun Data Analytics mark"
    title: "Sun Data Analytics"
    right:
      - text: "Main Website"
        href: https://sun-dataanalytics.com

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: false
    page-layout: full
